import Header from "@/components/Header";
import "./globals.css";
import Link from "next/link";
import { Roboto } from "next/font/google";

const roboto = Roboto({
    weight: ['400', '700'],
    style: ['normal', 'italic'],
    subsets: ['latin'],
    display: 'swap',
    variable: "--roboto"
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${roboto.variable}`}>
      <body>
        <Header />
        {children}
        </body>
    </html>
  );
}
