

export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <h1>testing</h1>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Aspernatur amet, saepe eius laborum fuga perspiciatis. Ea adipisci dignissimos illo voluptatibus! Facilis repellat expedita sit quidem aliquam quia, facere laudantium sunt. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quia recusandae temporibus quasi nesciunt autem, odio explicabo facere soluta aut possimus non velit corrupti dolorum ipsam eius accusamus quibusdam labore voluptate. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Accusantium dignissimos corporis doloremque neque aspernatur incidunt reprehenderit excepturi nemo repudiandae enim quis et harum, impedit labore error laboriosam? Recusandae, dignissimos libero. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Excepturi, doloremque hic! Amet quibusdam quas, rem eaque et eligendi cupiditate aperiam illum tenetur dolorum sit rerum nam est nesciunt veritatis nisi? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repellat, vitae cum. Quisquam, aliquid libero? Quae inventore iure voluptatibus dolorem! Cupiditate consectetur sed recusandae, ipsa placeat harum voluptatibus incidunt nisi rerum?</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Aspernatur amet, saepe eius laborum fuga perspiciatis. Ea adipisci dignissimos illo voluptatibus! Facilis repellat expedita sit quidem aliquam quia, facere laudantium sunt. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quia recusandae temporibus quasi nesciunt autem, odio explicabo facere soluta aut possimus non velit corrupti dolorum ipsam eius accusamus quibusdam labore voluptate. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Accusantium dignissimos corporis doloremque neque aspernatur incidunt reprehenderit excepturi nemo repudiandae enim quis et harum, impedit labore error laboriosam? Recusandae, dignissimos libero. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Excepturi, doloremque hic! Amet quibusdam quas, rem eaque et eligendi cupiditate aperiam illum tenetur dolorum sit rerum nam est nesciunt veritatis nisi? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repellat, vitae cum. Quisquam, aliquid libero? Quae inventore iure voluptatibus dolorem! Cupiditate consectetur sed recusandae, ipsa placeat harum voluptatibus incidunt nisi rerum?</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Aspernatur amet, saepe eius laborum fuga perspiciatis. Ea adipisci dignissimos illo voluptatibus! Facilis repellat expedita sit quidem aliquam quia, facere laudantium sunt. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quia recusandae temporibus quasi nesciunt autem, odio explicabo facere soluta aut possimus non velit corrupti dolorum ipsam eius accusamus quibusdam labore voluptate. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Accusantium dignissimos corporis doloremque neque aspernatur incidunt reprehenderit excepturi nemo repudiandae enim quis et harum, impedit labore error laboriosam? Recusandae, dignissimos libero. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Excepturi, doloremque hic! Amet quibusdam quas, rem eaque et eligendi cupiditate aperiam illum tenetur dolorum sit rerum nam est nesciunt veritatis nisi? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repellat, vitae cum. Quisquam, aliquid libero? Quae inventore iure voluptatibus dolorem! Cupiditate consectetur sed recusandae, ipsa placeat harum voluptatibus incidunt nisi rerum?</p>
    </main>
  );
}
